export const SOFTWARE: string[] = [
  'Another Volume Control Widget',
  'Auto Muter',
  'AutoHotkey_L',
  'DKVolume Control',
  'Exponential Volume Control',
  'FlashMute',
  'Global Audio Control',
  'MiniMute',
  'MiniVol XP',
  'Mixer Controlling Component',
  'Mute on Lock Portable',
  'Mute on Lock',
  'MuteTab',
  'My Volume',
  'Rewind Volume',
  'SoundOfSilence',
  'The Mutex',
  'VolTimer',
  'Volume Control Widget',
  'VolumeControl',
];
